FROM golang:alpine AS binarybuilder
RUN apk --no-cache --no-progress add \
    gcc \
    musl-dev
WORKDIR /dashboard
COPY . .
RUN cd cmd/dashboard \
    && go build -o app -ldflags="-s -w"

FROM alpine:latest
RUN apk --no-cache --no-progress add \
    ca-certificates \
    tzdata
WORKDIR /dashboard
COPY ./resource ./resource
COPY --from=binarybuilder /dashboard/cmd/dashboard/app ./app

VOLUME ["/dashboard/data"]
EXPOSE 3000
CMD ["/dashboard/app"]